color_palette: AppColors
icon_set: FluentIcons
widgets:
  Button:
    code: button
    text: $variable
    text2:
      t: $variable
    height:
      h: $
  # Container:
  #   code: container
  #   space: $padding
  #   overflow:
  #     enum: TextOverflow
  #     oe: ellipsis
  #     oc: clip
  #     of: fade
  #   height:
  #     h: '$'
  #   radius:
  #     r: 'BorderRadius.circular($)'
  #   bigsq: 'width: 200, height: 200' # direct substitution, like a macro
  #   _construct: # optional; by default just lumps all properties together
  #     - width
  #     - height
  #     - color
  #     - padding
  #     - alignment
  #     - decoration:
  #         - BoxDecoration
  #         - radius
  #         - border
  #     - another:
  #         - test
